[build]
  builder = "dockerfile"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "/start.sh"
  # Skip health checks for deployment
  # healthcheckPath = "/health"
  # healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[environment]
  NODE_ENV = "production"
