version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://synergy_user:synergy_pass@postgres:5432/synergysphere?schema=public
      - JWT_SECRET=your-production-jwt-secret-key
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: synergysphere
      POSTGRES_USER: synergy_user
      POSTGRES_PASSWORD: synergy_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synergy_user -d synergysphere"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
